
alias vi='vim'

# powershell {{

function _update_ps1() {
	PS1="$(~/powerline-shell.py $? 2> /dev/null)"
}

if [ "$TERM" != "linux" ]; then
	PROMPT_COMMAND="_update_ps1; $PROMPT_COMMAND"
fi

# }}

# mupweb {{

set -a  # auto-export all subequent env variable assignments
source $HOME/.mupweb.config
set +a  # turn off auto-export of env variables

# }}

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/ivy/Programming/google-cloud-sdk/path.bash.inc' ]; then source '/Users/ivy/Programming/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/ivy/Programming/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/ivy/Programming/google-cloud-sdk/completion.bash.inc'; fi

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

umask 002
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
